package com.irurueta.navigation.inertial.calibration;

/**
 * Interface defining events generated by this detector.
 */
public interface StaticIntervalDetectorListener {
    /**
     * Called when initial static period starts so that base noise level
     * starts being estimated.
     *
     * @param detected detector that raised the event.
     */
    void onInitializationStarted(final StaticIntervalDetector detected);

    /**
     * Called when initial static period successfully completes and base
     * noise level is estimated so that static and dynamic periods can be
     * detected.
     *
     * @param detected       detector that raised the event.
     * @param baseNoiseLevel base accelerometer noise level expressed in meters per squared second (m/s^2).
     */
    void onInitializationCompleted(final StaticIntervalDetector detected,
                                   final double baseNoiseLevel);

    /**
     * Called when an error is detected during initialization because there has been
     * excessive movement forces.
     *
     * @param detector                detector that raised the event.
     * @param accumulatedNoiseLevel   accumulated noise level expressed in meters per squared second (m/s^2).
     * @param instantaneousNoiseLevel instantaneous noise level expressed in meters per squared second (m/s^2).
     * @param reason                  reason why error was detected.
     */
    void onError(final StaticIntervalDetector detector,
                 final double accumulatedNoiseLevel,
                 final double instantaneousNoiseLevel,
                 final StaticIntervalDetector.ErrorReason reason);

    /**
     * Called when a static interval has been detected after initialization.
     *
     * @param detector detector that raised the event.
     */
    void onStaticIntervalDetected(final StaticIntervalDetector detector);

    /**
     * Called when a dynamic interval has been detected after initialization.
     *
     * @param detector detector that raised the event.
     * @param avgSpecificForceX average x-coordinate of specific force during last
     *                          static period expressed in meters per squared
     *                          second (m/s^2).
     * @param avgSpecificForceY average y-coordinate of specific force during last
     *                          static period expressed in meters per squared
     *                          second (m/s^2).
     * @param avgSpecificForceZ average z-coordinate of specific force during last
     *                          static period expressed in meters per squared
     *                          second (m/s^2).
     */
    void onDynamicIntervalDetected(final StaticIntervalDetector detector,
                                   final double avgSpecificForceX,
                                   final double avgSpecificForceY,
                                   final double avgSpecificForceZ);

    /**
     * Called when detector is reset.
     *
     * @param detector detector that raised the event.
     */
    void onReset(final StaticIntervalDetector detector);
}
